COMPONENT=MultihopOscilloscopeAppC
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net/ -I$(TINYOS_OS_DIR)/lib/net/ctp  -I$(TINYOS_OS_DIR)/lib/net/4bitle

TINYOS_ROOT_DIR?=../..
include $(TINYOS_ROOT_DIR)/Makefile.include
