
all:
	make micaz sim
	g++ -g -c -o Driver.o Driver.c -I../../../tos/lib/tossim/ -I../../../tos/lib/net -I../../../tos/lib/net/collection
	g++ -o Driver Driver.o build/micaz/sim.o build/micaz/tossim.o


