COMPONENT=TestAppC
TOSMAKE_PATH += .
PFLAGS += -I$(TINYOS_OS_DIR)/lib/ppp
PFLAGS += -I$(TINYOS_OS_DIR)/lib/fragpool
PFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
PFLAGS += -I$(TINYOS_OS_DIR)/platforms/$(PLATFORM)/chips/msp430
TINYOS_ROOT_DIR?=../../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include

