COMPONENT=TestCollectionAppC

CFLAGS += -I$(TINYOS_OS_DIR)/lib/tosthreads/sensorboards/universal

CFLAGS += -I$(TINYOS_OS_DIR)/lib/tosthreads/lib/net/
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net/

CFLAGS += -I$(TINYOS_OS_DIR)/lib/tosthreads/lib/net/ctp
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net/ctp  -I$(TINYOS_OS_DIR)/lib/net/4bitle

TINYOS_ROOT_DIR?=../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include
