all: #libcoap.a
	@echo "Nothing to compile for TinyOS."
#	$(MAKE) $(MAKEFLAGS) ROLE=server coap-server
# 	$(MAKE) $(MAKEFLAGS) clean
# 	$(MAKE) $(MAKEFLAGS) ROLE=client coap-client


#CFLAGS += -ffunction-sections
#LDFLAGS += -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__

#CFLAGS += #-DSHORT_ERROR_RESPONSE -DNDEBUG

#APPS += libcoap

#include $(CONTIKI)/Makefile.include
