/**
 * This file is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * It includes values of some nesC constants from
 * /home/phihup/cvs/tinyos-2.x/tos/lib/serial/Serial.h.
 */

enum {
    SERIAL_HDLC_CTLESC_BYTE = 125,
    SERIAL_TOS_SERIAL_802_15_4_ID = 2,
    SERIAL_SERIAL_PROTO_ACK = 67,
    SERIAL_TOS_SERIAL_CC1000_ID = 1,
    SERIAL_SERIAL_PROTO_PACKET_NOACK = 69,
    SERIAL_SERIAL_PROTO_PACKET_UNKNOWN = 255,
    SERIAL_HDLC_FLAG_BYTE = 126,
    SERIAL_TOS_SERIAL_ACTIVE_MESSAGE_ID = 0,
    SERIAL_TOS_SERIAL_UNKNOWN_ID = 255,
    SERIAL_SERIAL_PROTO_PACKET_ACK = 68
};
