COMPONENT=TestAppC
TOSMAKE_PATH += ..
PFLAGS += -I$(TOSDIR)/lib/ppp
PFLAGS += -I$(TOSDIR)/lib/fragpool
PFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS += -I$(TOSDIR)/platforms/$(PLATFORM)/chips/msp430
include $(MAKERULES)
