COMPONENT=TestDisseminationAppC

### For Drip:
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I%T/lib/net/drip

### For DIP:
#CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I%T/lib/net/dip -I%T/lib/net/dip/interfaces

### For Dhv
#CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I%T/lib/net/dhv -I%T/lib/net/dhv/interfaces

TINYOS_ROOT_DIR?=../../..
include $(TINYOS_ROOT_DIR)/Makefile.include

