COMPONENT=TestAppC
TOSMAKE_PATH += ..
TOSMAKE_PATH += .
PFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
PFLAGS += -I$(TINYOS_OS_DIR)/lib/fragpool
PFLAGS += -I$(TINYOS_OS_DIR)/lib/ppp
TINYOS_ROOT_DIR?=../../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include

