COMPONENT=TestCollectionAppC

CFLAGS += -I$(TOSDIR)/lib/tosthreads/sensorboards/universal
CFLAGS += -I$(TOSDIR)/lib/tosthreads/lib/net/
CFLAGS += -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle

include $(MAKERULES)
