COMPONENT=TestAppC
PFLAGS += -DDEBUG_HDLC_FRAMING
PFLAGS += -I$(TINYOS_OS_DIR)/lib/ppp
PFLAGS += -I$(TINYOS_OS_DIR)/lib/fragpool
PFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
TINYOS_ROOT_DIR?=../../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include
