/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../LowPowerSensingConstants.h.
 */

public class Constants  {
    public static final byte MSG_QUEUE_SIZE = 50;
    public static final short SAMPLING_INTERVAL = 3000;
    public static final byte BASE_STATION_ADDR = 0;
    public static final short LPL_INTERVAL = 2000;
}
