/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialSampleMsg'
 * message type.
 */

public class SerialSampleMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 8;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 153;

    /** Create a new SerialSampleMsg of size 8. */
    public SerialSampleMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialSampleMsg of the given data_length. */
    public SerialSampleMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg with the given data_length
     * and base offset.
     */
    public SerialSampleMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg using the given byte array
     * as backing store.
     */
    public SerialSampleMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialSampleMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialSampleMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg embedded in the given message
     * at the given base offset.
     */
    public SerialSampleMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialSampleMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialSampleMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialSampleMsg> \n";
      try {
        s += "  [src_addr=0x"+Long.toHexString(get_src_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sample.sample_num=0x"+Long.toHexString(get_sample_sample_num())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sample.sin_value=0x"+Long.toHexString(get_sample_sin_value())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: src_addr
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'src_addr' is signed (false).
     */
    public static boolean isSigned_src_addr() {
        return false;
    }

    /**
     * Return whether the field 'src_addr' is an array (false).
     */
    public static boolean isArray_src_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'src_addr'
     */
    public static int offset_src_addr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'src_addr'
     */
    public static int offsetBits_src_addr() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'src_addr'
     */
    public int get_src_addr() {
        return (int)getUIntBEElement(offsetBits_src_addr(), 16);
    }

    /**
     * Set the value of the field 'src_addr'
     */
    public void set_src_addr(int value) {
        setUIntBEElement(offsetBits_src_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'src_addr'
     */
    public static int size_src_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'src_addr'
     */
    public static int sizeBits_src_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample.sample_num
    //   Field type: long
    //   Offset (bits): 16
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample.sample_num' is signed (false).
     */
    public static boolean isSigned_sample_sample_num() {
        return false;
    }

    /**
     * Return whether the field 'sample.sample_num' is an array (false).
     */
    public static boolean isArray_sample_sample_num() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample.sample_num'
     */
    public static int offset_sample_sample_num() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample.sample_num'
     */
    public static int offsetBits_sample_sample_num() {
        return 16;
    }

    /**
     * Return the value (as a long) of the field 'sample.sample_num'
     */
    public long get_sample_sample_num() {
        return (long)getUIntBEElement(offsetBits_sample_sample_num(), 32);
    }

    /**
     * Set the value of the field 'sample.sample_num'
     */
    public void set_sample_sample_num(long value) {
        setUIntBEElement(offsetBits_sample_sample_num(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample.sample_num'
     */
    public static int size_sample_sample_num() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample.sample_num'
     */
    public static int sizeBits_sample_sample_num() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample.sin_value
    //   Field type: int
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample.sin_value' is signed (false).
     */
    public static boolean isSigned_sample_sin_value() {
        return false;
    }

    /**
     * Return whether the field 'sample.sin_value' is an array (false).
     */
    public static boolean isArray_sample_sin_value() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample.sin_value'
     */
    public static int offset_sample_sin_value() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample.sin_value'
     */
    public static int offsetBits_sample_sin_value() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'sample.sin_value'
     */
    public int get_sample_sin_value() {
        return (int)getUIntBEElement(offsetBits_sample_sin_value(), 16);
    }

    /**
     * Set the value of the field 'sample.sin_value'
     */
    public void set_sample_sin_value(int value) {
        setUIntBEElement(offsetBits_sample_sin_value(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample.sin_value'
     */
    public static int size_sample_sin_value() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample.sin_value'
     */
    public static int sizeBits_sample_sin_value() {
        return 16;
    }

}
