/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialRequestSamplesMsg'
 * message type.
 */

public class SerialRequestSamplesMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 146;

    /** Create a new SerialRequestSamplesMsg of size 6. */
    public SerialRequestSamplesMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialRequestSamplesMsg of the given data_length. */
    public SerialRequestSamplesMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg with the given data_length
     * and base offset.
     */
    public SerialRequestSamplesMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg using the given byte array
     * as backing store.
     */
    public SerialRequestSamplesMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialRequestSamplesMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialRequestSamplesMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg embedded in the given message
     * at the given base offset.
     */
    public SerialRequestSamplesMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialRequestSamplesMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialRequestSamplesMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialRequestSamplesMsg> \n";
      try {
        s += "  [addr=0x"+Long.toHexString(get_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sample_num=0x"+Long.toHexString(get_sample_num())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: addr
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'addr' is signed (false).
     */
    public static boolean isSigned_addr() {
        return false;
    }

    /**
     * Return whether the field 'addr' is an array (false).
     */
    public static boolean isArray_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'addr'
     */
    public static int offset_addr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'addr'
     */
    public static int offsetBits_addr() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'addr'
     */
    public int get_addr() {
        return (int)getUIntBEElement(offsetBits_addr(), 16);
    }

    /**
     * Set the value of the field 'addr'
     */
    public void set_addr(int value) {
        setUIntBEElement(offsetBits_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'addr'
     */
    public static int size_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'addr'
     */
    public static int sizeBits_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample_num
    //   Field type: long, unsigned
    //   Offset (bits): 16
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample_num' is signed (false).
     */
    public static boolean isSigned_sample_num() {
        return false;
    }

    /**
     * Return whether the field 'sample_num' is an array (false).
     */
    public static boolean isArray_sample_num() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample_num'
     */
    public static int offset_sample_num() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample_num'
     */
    public static int offsetBits_sample_num() {
        return 16;
    }

    /**
     * Return the value (as a long) of the field 'sample_num'
     */
    public long get_sample_num() {
        return (long)getUIntBEElement(offsetBits_sample_num(), 32);
    }

    /**
     * Set the value of the field 'sample_num'
     */
    public void set_sample_num(long value) {
        setUIntBEElement(offsetBits_sample_num(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample_num'
     */
    public static int size_sample_num() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample_num'
     */
    public static int sizeBits_sample_num() {
        return 32;
    }

}
