COMPONENT=NWK

PFLAGS += 	-I$(TOSROOT)/tos/ieee802154/includes \
			-I$(TOSROOT)/tos/ieee802154/mac \
			-I$(TOSROOT)/tos/ieee802154/phy \
			-I$(TOSROOT)/tos/ieee802154/timerasync \
			-I$(TOSROOT)/tos/ieee802154/interfaces \
			-I$(TOSROOT)/tos/ieee802154/interfaces/mac \
			-I$(TOSROOT)/tos/ieee802154/interfaces/phy \
			-I$(TOSROOT)/tos/chips/cc2420/ieee802154
include $(MAKERULES)

