COMPONENT=TCPEchoC

# uncomment this for network programming support
# BOOTLOADER=tosboot

# radio opts
CFLAGS += -DCC2420_DEF_CHANNEL=17
# CFLAGS += -DCC2420_DEF_RFPOWER=4


# CFLAGS += -DNO_LIB6LOWPAN_ASCII

# if this is set, motes will send debugging information to the address
# listed.
# CFLAGS += -DREPORT_DEST=\"2001:470:1f04:56d::64\"

# sim/test harness
# CFLAGS += -I../IPBaseStation
# CFLAGS += -DDBG_TRACK_FLOWS -DDBG_FLOWS_REPORT

# printf debugs.  works only on telosb/tmote sky
# CFLAGS += -DPRINTFUART_ENABLED


include $(MAKERULES)

