// $Id: net_tinyos_util_Env.h,v 1.3 2006-11-07 19:30:42 scipio Exp $

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tinyos_util_Env */

#ifndef _Included_net_tinyos_util_Env
#define _Included_net_tinyos_util_Env
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: loaded */
/*
 * Class:     net_tinyos_util_Env
 * Method:    igetenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_tinyos_util_Env_igetenv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
