COMPONENT=Test_APL

PFLAGS += 	-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/includes \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/macTDBS \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/phy \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/timerasyncTDBS \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/interfaces \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/interfaces/mac \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/interfaces/phy \
			-I$(TOSROOT)/tos/lib/net/zigbee/cc2420 \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/interfaces/nwk \
			-I$(TOSROOT)/tos/lib/net/zigbee/ieee802154/nwk
			
include $(MAKERULES)

