COMPONENT = TestAppC
PFLAGS += -DTEST_FRAGMENT_POOL
PFLAGS += -I$(TINYOS_OS_DIR)/lib/fragpool
PFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
TINYOS_ROOT_DIR?=../../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include
