COMPONENT=LowPowerSensingPeriodicSamplerAppC
CFLAGS += -I.. -I../sampleLog
CFLAGS += -I.. -I../universal_sensors
CFLAGS += -DLOW_POWER_LISTENING
#CFLAGS += -I.. -I../tmote_onboard_sensors
#CFLAGS += -DCC1K_DEFAULT_FREQ=CC1K_914_077_MHZ

include $(MAKERULES)
