COMPONENT=GTSManagementExampleC

PFLAGS += 	-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/includes \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/mac \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/phy \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/timerasync \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/interfaces \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/interfaces/mac \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/ieee802154/interfaces/phy \
			-I$(TINYOS_OS_DIR)/lib/net/zigbee/cc2420
TINYOS_ROOT_DIR?=../../../../../..
include $(TINYOS_ROOT_DIR)/Makefile.include
