COMPONENT=MultihopOscilloscopeAppC
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net/ -I$(TINYOS_OS_DIR)/lib/net/lqi -I$(TINYOS_OS_DIR)/chips/cc2420/interfaces

TINYOS_ROOT_DIR?=../../..
include $(TINYOS_ROOT_DIR)/Makefile.include
