/*
 * Copyright (c) 2007, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * Author: Miklos Maroti
 */

#ifndef __RF2XX_H__
#define __RF2XX_H__

/* Set RF2XX_CHIPSET to one of these to enable specific features */
#define RF230_CHIPSET	0
#define RF212_CHIPSET	1

enum rf2xx_registers_enum
{
	RF2XX_TRX_STATUS = 0x01,
	RF2XX_TRX_STATE = 0x02,
	RF2XX_TRX_CTRL_0 = 0x03,
	RF2XX_PHY_TX_PWR = 0x05,
	RF2XX_PHY_RSSI = 0x06,
	RF2XX_PHY_ED_LEVEL = 0x07,
	RF2XX_PHY_CC_CCA = 0x08,
	RF2XX_CCA_THRES = 0x09,
	RF2XX_IRQ_MASK = 0x0E,
	RF2XX_IRQ_STATUS = 0x0F,
	RF2XX_VREG_CTRL = 0x10,
	RF2XX_BATMON = 0x11,
	RF2XX_XOSC_CTRL = 0x12,
	RF2XX_PLL_CF = 0x1A,
	RF2XX_PLL_DCU = 0x1B,
	RF2XX_PART_NUM = 0x1C,
	RF2XX_VERSION_NUM = 0x1D,
	RF2XX_MAN_ID_0 = 0x1E,
	RF2XX_MAN_ID_1 = 0x1F,
	RF2XX_SHORT_ADDR_0 = 0x20,
	RF2XX_SHORT_ADDR_1 = 0x21,
	RF2XX_PAN_ID_0 = 0x22,
	RF2XX_PAN_ID_1 = 0x23,
	RF2XX_IEEE_ADDR_0 = 0x24,
	RF2XX_IEEE_ADDR_1 = 0x25,
	RF2XX_IEEE_ADDR_2 = 0x26,
	RF2XX_IEEE_ADDR_3 = 0x27,
	RF2XX_IEEE_ADDR_4 = 0x28,
	RF2XX_IEEE_ADDR_5 = 0x29,
	RF2XX_IEEE_ADDR_6 = 0x2A,
	RF2XX_IEEE_ADDR_7 = 0x2B,
	RF2XX_XAH_CTRL = 0x2C,
	RF2XX_CSMA_SEED_0 = 0x2D,
	RF2XX_CSMA_SEED_1 = 0x2E,
};

enum rf2xx_trx_register_enums
{
	RF2XX_CCA_DONE = 1 << 7,
	RF2XX_CCA_STATUS = 1 << 6,
	RF2XX_TRX_STATUS_MASK = 0x1F,
	RF2XX_P_ON = 0,
	RF2XX_BUSY_RX = 1,
	RF2XX_BUSY_TX = 2,
	RF2XX_RX_ON = 6,
	RF2XX_TRX_OFF = 8,
	RF2XX_PLL_ON = 9,
	RF2XX_SLEEP = 15,
	RF2XX_BUSY_RX_AACK = 16,
	RF2XX_BUSR_TX_ARET = 17,
	RF2XX_RX_AACK_ON = 22,
	RF2XX_TX_ARET_ON = 25,
	RF2XX_RX_ON_NOCLK = 28,
	RF2XX_AACK_ON_NOCLK = 29,
	RF2XX_BUSY_RX_AACK_NOCLK = 30,
	RF2XX_STATE_TRANSITION_IN_PROGRESS = 31,
	RF2XX_TRAC_STATUS_MASK = 0xE0,
	RF2XX_TRAC_SUCCESS = 0,
	RF2XX_TRAC_CHANNEL_ACCESS_FAILURE = 3 << 5,
	RF2XX_TRAC_NO_ACK = 5 << 5,
	RF2XX_TRX_CMD_MASK = 0x1F,
	RF2XX_NOP = 0,
	RF2XX_TX_START = 2,
	RF2XX_FORCE_TRX_OFF = 3,
};

enum rf2xx_phy_register_enums
{
	RF2XX_TX_AUTO_CRC_ON = 1 << 7,
	RF2XX_TX_PWR_MASK = 0x0F,
	RF2XX_TX_PWR_DEFAULT = 0,
	RF2XX_RSSI_MASK = 0x1F,
	RF2XX_CCA_REQUEST = 1 << 7,
	RF2XX_CCA_MODE_0 = 0 << 5,
	RF2XX_CCA_MODE_1 = 1 << 5,
	RF2XX_CCA_MODE_2 = 2 << 5,
	RF2XX_CCA_MODE_3 = 3 << 5,
	RF2XX_CHANNEL_DEFAULT = 11,
	RF2XX_CHANNEL_MASK = 0x1F,
	RF2XX_CCA_CS_THRES_SHIFT = 4,
	RF2XX_CCA_ED_THRES_SHIFT = 0,
};

enum rf2xx_irq_register_enums
{
	RF2XX_IRQ_BAT_LOW = 1 << 7,
	RF2XX_IRQ_TRX_UR = 1 << 6,
	RF2XX_IRQ_TRX_END = 1 << 3,
	RF2XX_IRQ_RX_START = 1 << 2,
	RF2XX_IRQ_PLL_UNLOCK = 1 << 1,
	RF2XX_IRQ_PLL_LOCK = 1 << 0,
};

enum rf2xx_control_register_enums
{
	RF2XX_AVREG_EXT = 1 << 7,
	RF2XX_AVDD_OK = 1 << 6,
	RF2XX_DVREG_EXT = 1 << 3,
	RF2XX_DVDD_OK = 1 << 2,
	RF2XX_BATMON_OK = 1 << 5,
	RF2XX_BATMON_VHR = 1 << 4,
	RF2XX_BATMON_VTH_MASK = 0x0F,
	RF2XX_XTAL_MODE_OFF = 0 << 4,
	RF2XX_XTAL_MODE_EXTERNAL = 4 << 4,
	RF2XX_XTAL_MODE_INTERNAL = 15 << 4,
};

enum rf2xx_pll_register_enums
{
	RF2XX_PLL_CF_START = 1 << 7,
	RF2XX_PLL_DCU_START = 1 << 7,
};

enum rf2xx_spi_command_enums
{
	RF2XX_CMD_REGISTER_READ = 0x80,
	RF2XX_CMD_REGISTER_WRITE = 0xC0,
	RF2XX_CMD_REGISTER_MASK = 0x3F,
	RF2XX_CMD_FRAME_READ = 0x20,
	RF2XX_CMD_FRAME_WRITE = 0x60,
	RF2XX_CMD_SRAM_READ = 0x00,
	RF2XX_CMD_SRAM_WRITE = 0x40,
};

#endif//__RF2XX_H__
