COMPONENT=TestSerialC
CFLAGS += -I%T/lib/oski
#BUILD_EXTRA_DEPS += TestSerial.class
#CLEAN_EXTRA = *.class TestSerialMsg.java

#TestSerial.class: $(wildcard *.java) TestSerialMsg.java
#	javac *.java

#TestSerialMsg.java:
#	mig java -target=null $(CFLAGS) -java-classname=TestSerialMsg TestSerial.h TestSerialMsg -o $@


include $(MAKERULES)

