 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # /opt/tinyos-2.x/tos/lib/serial/Serial.h.
 #/

class Serial:
    HDLC_CTLESC_BYTE = 125
    SERIAL_PROTO_ACK = 67
    TOS_SERIAL_802_15_4_ID = 2
    SERIAL_PROTO_PACKET_UNKNOWN = 255
    SERIAL_PROTO_PACKET_NOACK = 69
    TOS_SERIAL_CC1000_ID = 1
    HDLC_FLAG_BYTE = 126
    TOS_SERIAL_ACTIVE_MESSAGE_ID = 0
    SERIAL_PROTO_PACKET_ACK = 68
    TOS_SERIAL_UNKNOWN_ID = 255

