PLATFORMS = telosb micaz
TKN154_PLATFORM_INCLUDE?=$(TOSDIR)/platforms/$(PLATFORM)/mac/tkn154/Makefile.include

CFLAGS += -I$(TOSDIR)/lib/mac/tkn154 \
	-I$(TOSDIR)/lib/mac/tkn154/dummies \
	-I$(TOSDIR)/lib/mac/tkn154/interfaces/MCPS \
	-I$(TOSDIR)/lib/mac/tkn154/interfaces/MLME \
	-I$(TOSDIR)/lib/mac/tkn154/interfaces/private \
	-I$(TOSDIR)/lib/mac/tkn154/interfaces/public

TOSMAKE_PATH += $(TOSDIR)/../apps/tests/tkn154/extras

# legacy
ifdef IEEE154_EXTENDED_ADDRESS
$(error To set the extended address of a device to X pass 'extaddr,X' to the make system (e.g. "make telosb extaddr,0x012345"))
endif

# legacy
ifdef TKN154_DEBUG
$(error To enable debug mode pass 'tkn154debug' to the make system (e.g. "make telosb tkn154debug"))
endif

# parses the PLATFORM variable
include $(MAKERULES)

# checks whether the target platform is supported by the application;
# the application Makefile can define PLATFORMS as a whitespace-separated
# list of supported platforms
ifneq ($(PLATFORM),)
  ifneq ($(PLATFORMS),)
    ifeq ($(strip $(foreach platform,$(PLATFORMS),$(findstring $(platform),$(PLATFORM)))),)
      $(error The target platform is not supported by this application - supported platforms are: $(PLATFORMS))
    endif
  endif
  include $(TKN154_PLATFORM_INCLUDE)
endif

