.TH tos-install-jni 1 "Feb 3, 2006"
.LO 1
.SH NAME

tos-install-jni - Install TinyOS JNI libraries
.SH SYNOPSIS

\fBtos-install-jni\fR
.SH DESCRIPTION

\fBtos-install-jni\fR install's TinyOS's JNI libraries in your Java
installation. On Linux and other similar operating systems,
\fBtos-install-jni\fR should be run as root. If \fBtos-install-jni\fR has
problems (fails to find Java, or installs files in an unexpected place),
see the \fBtos-locate-jre\fR man page for information on how your Java
installation is located.
.SH SEE ALSO

.IR tos-locate-jre (1)
