.TH tos-mote-key 1 "Feb 3, 2006"
.LO 1
.SH NAME

tos-mote-key - Manage TinySec keys
.SH SYNOPSIS

\fBtos-mote-key\fR [\fB-kf \fIkeyfile\fR] [\fB-kn \fIkeyname\fR]
.SH DESCRIPTION

\fBtos-mote-key\fR manages TinySec keys. TinySec is an encryption system
for mica and mica2 motes under TinyOS 1.1. See the TinySec documentation
for more details.
