.TH tos-ident-flags 1 "Feb 3, 2006"
.LO 1
.SH NAME

tos-ident-flags - generate compile-time flags identifying a program build
.SH SYNOPSIS

\fBtos-ident-flags\fR \fIprogram-name\fR
.SH DESCRIPTION

\fBtos-ident-flags\fR prints a set of \fB-D\fIname\fB=\fIvalue\fR options
that identify a build of \fIprogram-name\fR. It is used to embed build
information in a TinyOS executable.
