TOSTHREAD_MAIN=TestCollection.c

PFLAGS += -DTOSTHREAD_MAIN_STACK_SIZE=800

CFLAGS += -I$(TOSDIR)/lib/tosthreads/sensorboards/universal

CFLAGS += -I$(TOSDIR)/lib/tosthreads/lib/net/
CFLAGS += -I$(TOSDIR)/lib/net/

CFLAGS += -I$(TOSDIR)/lib/tosthreads/lib/net/ctp
CFLAGS += -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle

include $(MAKERULES)
