package net.tinyos.comm;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class TOSCommJNI {

  static { net.tinyos.util.TOSLibraryLoader.load("toscomm"); }

  public final static native void NativeSerial_setSerialPortParams(long jarg1, int jarg2, int jarg3, int jarg4, boolean jarg5);
  public final static native int NativeSerial_getBaudRate(long jarg1);
  public final static native int NativeSerial_getDataBits(long jarg1);
  public final static native int NativeSerial_getStopBits(long jarg1);
  public final static native boolean NativeSerial_getParity(long jarg1);
  public final static native void NativeSerial_notifyOn(long jarg1, int jarg2, boolean jarg3);
  public final static native boolean NativeSerial_isNotifyOn(long jarg1, int jarg2);
  public final static native boolean NativeSerial_waitForEvent(long jarg1);
  public final static native boolean NativeSerial_cancelWait(long jarg1);
  public final static native boolean NativeSerial_didEventOccur(long jarg1, int jarg2);
  public final static native void NativeSerial_setDTR(long jarg1, boolean jarg2);
  public final static native void NativeSerial_setRTS(long jarg1, boolean jarg2);
  public final static native boolean NativeSerial_isDTR(long jarg1);
  public final static native boolean NativeSerial_isRTS(long jarg1);
  public final static native boolean NativeSerial_isCTS(long jarg1);
  public final static native boolean NativeSerial_isDSR(long jarg1);
  public final static native boolean NativeSerial_isRI(long jarg1);
  public final static native boolean NativeSerial_isCD(long jarg1);
  public final static native void NativeSerial_sendBreak(long jarg1, int jarg2);
  public final static native long new_NativeSerial(String jarg1);
  public final static native void delete_NativeSerial(long jarg1);
  public final static native void NativeSerial_close(long jarg1);
  public final static native int NativeSerial_available(long jarg1);
  public final static native int NativeSerial_read__SWIG_0(long jarg1);
  public final static native int NativeSerial_read__SWIG_1(long jarg1, byte[] jarg2, int jarg3, int jarg4);
  public final static native int NativeSerial_write__SWIG_0(long jarg1, int jarg2);
  public final static native int NativeSerial_write__SWIG_1(long jarg1, byte[] jarg2, int jarg3, int jarg4);
  public final static native String NativeSerial_getTOSCommMap();
}
